---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# cebrap.lab online -  Raspagem de dados com R

Para saber de próximos oferecimentos, entre em contato com <cebrap.lab@cebrap.org.br>


## Informações gerais

- **Ministrante:** [Beatriz Milz](https://beamilz.com/about/)

- **Data/horário:** 21 a 25 de outubro/2024;
  - Segunda, Quarta e Sexta: aula ao vivo, online, das 19h00 às 22h00.
  - Terça e quinta: haverão tarefas para casa, para praticar os conceitos.

- **Inscrições:** <https://cursos.cebrap.org.br/cursos/raspagem-de-dados-com-r/>

## Descrição

O curso “Raspagem de dados com R” abordará uma introdução ao uso da linguagem de programação R para obter dados da internet através de uma técnica chamada raspagem de dados (web scraping).

O curso abordará conceitos relevantes, como: 

  - o que é raspagem de dados?; 

  - política de uso; 

  - tipos de problemas de raspagem (APIs (disponíveis e “escondidas”);

  - raspagem de HTML (estático e dinâmico), etc);

  - entre outros. 

O curso apresentará exemplos de raspagem de dados em todas as aulas, raspando sites que são interessantes no contexto brasileiro!

Todas as ferramentas utilizadas são gratuitas: utilizaremos a linguagem de programação R, o RStudio, e os pacotes tidyverse, httr, rvest, xml2, purrr, entre outros. 

O curso tem como **público alvo**  pessoasque tenham interesse em obter dados através da técnica de raspagem de dados na internet utilizando R, e que tenham familiaridade fazendo as seguintes tarefas em R: importar bases de dados, filtrar linhas, selecionar colunas, agrupar a base, criar sumarizações, criar novas colunas (pacotes readr e dplyr do tidyverse).

## Materiais

- [Pasta compactada (`.zip`) com materiais do curso: scripts, dados, slides, exercícios, etc.](https://github.com/beatrizmilz/2024-10-cebrap-lab-web-scraping/archive/refs/heads/main.zip)

### Slides

- [Slide de apresentação do curso](https://beatrizmilz.github.io/2024-10-cebrap-lab-web-scraping/slides/introducao-ao-curso.html)

- [APIs](https://beatrizmilz.github.io/2024-10-cebrap-lab-web-scraping/slides/api.html)



### Scripts pós aula

Em breve!


### Exercícios

Em breve!


## Materiais para revisão do conteúdo básico

- [Introdução à análise de dados no R - Utilizando dados públicos e registros administrativos brasileiros](https://ipeadata-lab.github.io/curso_r_intro_202409/)

- [Material do curso de Introdução ao R - 2024 (ministrado por Beatriz Milz)](https://beatrizmilz.github.io/2024-08-cebrap-lab-intro-R/)

- [Material do curso de Visualização de dados com R - 2024 (ministrado por Beatriz Milz)](https://beatrizmilz.github.io/2024-09-cebrap-lab-viz/)

- [Livro online, gratuito e em português: R for Data Science](https://cienciadedatos.github.io/pt-r4ds/)

- [Livro online e gratuito e em português: Ciência de Dados em R](https://livro.curso-r.com/7-2-dplyr.html)
